# Generated by Django 2.1.3 on 2019-03-10 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('tiekejas', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('dok_nr', models.IntegerField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipas', models.CharField(max_length=50)),
                ('aktyvus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keeper_name', models.CharField(default=None, max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_public', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(default=None, related_name='keepers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expensetypes',
            name='keeper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='islaidos_app.Keeper'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='keeper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='islaidos_app.Keeper'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='tipas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islaidos_app.ExpenseTypes'),
        ),
    ]
