# Generated by Django 2.1.3 on 2018-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Islaidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipas', models.CharField(max_length=100)),
                ('tiekejas', models.CharField(max_length=50)),
                ('dok_nr', models.IntegerField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
