# Generated by Django 2.1.3 on 2019-01-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islaidos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('tiekejas', models.CharField(max_length=100)),
                ('dok_nr', models.IntegerField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipas', models.CharField(max_length=50)),
                ('aktyvus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keeper_name', models.CharField(default=None, max_length=50)),
                ('user_name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Islaidos',
        ),
        migrations.AddField(
            model_name='expensetypes',
            name='keeper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='islaidos_app.Keeper'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='keeper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='islaidos_app.Keeper'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='tipas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islaidos_app.ExpenseTypes'),
        ),
    ]
