# Generated by Django 2.1.3 on 2019-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islaidos_app', '0002_auto_20190127_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='product_service',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
