# Generated by Django 2.1.3 on 2019-01-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('islaidos_app', '0003_expenses_product_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='product_service',
            new_name='description',
        ),
    ]
